pipeline:
    name: build
    stages:
        - name: dependencies
          tasks:
            - name: download
              command: go
              args:
                - mod
                - download
            - name: verify
              command: go
              args:
                - mod
                - verify
        - name: compile
          tasks:
            - name: linux-amd64
              command: go
              args:
                - build
                - -o
                - ${ANVIL_OUTPUT_DIR}/anvil-linux-amd64
                - .
              env:
                GOOS: linux
                GOARCH: amd64
            - name: linux-arm64
              command: go
              args:
                - build
                - -o
                - ${ANVIL_OUTPUT_DIR}/anvil-linux-arm64
                - .
              env:
                GOOS: linux
                GOARCH: arm64
            - name: darwin-amd64
              command: go
              args:
                - build
                - -o
                - ${ANVIL_OUTPUT_DIR}/anvil-darwin-amd64
                - .
              env:
                GOOS: darwin
                GOARCH: amd64
            - name: darwin-arm64
              command: go
              args:
                - build
                - -o
                - ${ANVIL_OUTPUT_DIR}/anvil-darwin-arm64
                - .
              env:
                GOOS: darwin
                GOARCH: arm64
