<script>
  import { onMount } from 'svelte'
  import { invoke } from '@tauri-apps/api/core'
  import { open } from '@tauri-apps/plugin-dialog'
  let forms = {}, values = {}, errors = {}, installDir = '', error = '', done = false, busy = false, productName = 'Anvil', version = ''
  $: entries = Object.entries(forms), fields = entries.flatMap(([name, form]) => (form.fields || []).filter((f) => visible(name, f)).map((f) => ({ ...f, form: name }))), filled = fields.filter((f) => values[f.form]?.[f.name]).length, progress = done ? 100 : fields.length ? Math.round(filled / fields.length * 100) : 0
  onMount(async () => { try { forms = await invoke('get_forms_json') || {} } catch { forms = {} }; try { const meta = await invoke('get_app_metadata'); productName = meta?.name || productName; version = meta?.version || '' } catch {}; for (const [name, form] of entries) { values[name] = {}; errors[name] = {}; for (const field of form.fields || []) values[name][field.name] = '' } })
  const visible = (name, field) => !field.when || values[name]?.[field.when.field] === field.when.value
  function valid(field, value, name) { const all = values[name] || {}; if (field.required && !value.trim()) return `${field.name} is required`; if (field.minLength != null && value && value.length < field.minLength) return `${field.name} must be at least ${field.minLength} characters`; if (field.type === 'email' && value && !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(value)) return `${field.name} must be a valid email`; if (field.type === 'number' && value && !/^-?[0-9]+(\.[0-9]+)?$/.test(value)) return `${field.name} must be a valid number`; if (field.confirmation && value !== all[field.confirmation]) return `${field.name} does not match ${field.confirmation}`; if (field.pattern && value) { try { if (!new RegExp(field.pattern).test(value)) return `${field.name} does not match pattern` } catch {} }; if (field.type === 'select' && value && field.options?.length && !field.options.includes(value)) return `${field.name} must be one of [${field.options.join(', ')}]`; return '' }
  function input(name, field, event) { values[name][field.name] = event.target.value; errors[name][field.name] = valid(field, event.target.value, name); error = errors[name][field.name] }
  function payload() { const out = {}; for (const [name, form] of entries) { out[name] = {}; for (const field of form.fields || []) if (visible(name, field)) out[name][field.name] = values[name][field.name] || '' }; return out }
  async function choose() { try { const selected = await open({ directory: true, multiple: false, title: 'Choose installation folder' }); if (typeof selected === 'string') installDir = await invoke('choose_install_dir', { path: selected }) } catch (e) { error = String(e) } }
  async function install() { error = ''; if (!installDir) { error = 'Choose an install folder'; return }; for (const [name, form] of entries) for (const field of form.fields || []) if (visible(name, field) && (errors[name][field.name] = valid(field, values[name][field.name] || '', name))) { error = errors[name][field.name]; return }; busy = true; try { const data = payload(); await invoke('collect_forms', { forms: data }); await invoke('verify_before_extract'); await invoke('extract_payload', { destDir: installDir }); await invoke('apply_setup', { forms: data, destDir: installDir }); done = true } catch (e) { error = String(e) } finally { busy = false } }
</script>
<svelte:head><title>{productName} installer</title></svelte:head>
<main><header><div class="mark">A</div><div><p class="eyebrow">{productName} setup</p><h1>Install {productName}</h1><p>Configure your installation, then let the installer handle the rest.</p></div>{#if version}<small>v{version}</small>{/if}</header><div class="steps"><b>1 <span>Configure</span></b><i></i><b class:active={done}>2 <span>Complete</span></b></div><div class="track"><span style={`width:${progress}%`}></span></div>{#if !done}<section class="folder"><div><em>Required</em><h2>Installation folder</h2><p>Choose where {productName} should be installed.</p></div><button class="secondary" on:click={choose}>Browse folders</button>{#if installDir}<code>{installDir}</code>{:else}<p class="muted">No folder selected yet</p>{/if}</section>{#each entries as [name, form]}<section><em>Step {entries.findIndex((item) => item[0] === name) + 1}</em><h2>{form.title || name}</h2>{#each form.fields || [] as field}{#if visible(name, field)}<div class:bad={errors[name]?.[field.name]} class="field"><label for={`${name}-${field.name}`}>{field.label || field.name}{field.required ? ' *' : ''}</label>{#if field.type === 'select'}<select id={`${name}-${field.name}`} value={values[name][field.name]} on:change={(e)=>input(name,field,e)}><option value="">Select an option</option>{#each field.options || [] as option}<option value={option}>{option}</option>{/each}</select>{:else if field.type === 'textarea'}<textarea id={`${name}-${field.name}`} value={values[name][field.name]} on:input={(e)=>input(name,field,e)} rows="4"></textarea>{:else}<input id={`${name}-${field.name}`} type={field.type} value={values[name][field.name]} on:input={(e)=>input(name,field,e)} aria-invalid={!!errors[name]?.[field.name]}>{/if}{#if errors[name]?.[field.name]}<span role="alert">{errors[name][field.name]}</span>{/if}</div>{/if}{/each}</section>{/each}<button class="primary" disabled={busy} on:click={install}>{busy ? 'Installing…' : `Install ${productName}`}</button>{:else}<div class="success" role="status">✓ <div><h2>Installation complete</h2><p>{productName} is ready to use.</p></div></div>{/if}{#if error}<p class="error" role="alert">{error}</p>{/if}<footer>Powered by <strong>Anvil</strong> · Maleolabs</footer></main>
<style>:global(*){box-sizing:border-box}:global(body){margin:0;background:#f5f7fa;color:#16212b;font:14px/1.5 Inter,system-ui,sans-serif}main{max-width:680px;margin:auto;padding:34px 28px}header{display:flex;gap:16px;align-items:flex-start;margin-bottom:30px}.mark{background:#123b53;color:#d9f06a;border-radius:12px;width:44px;height:44px;display:grid;place-items:center;font-size:22px;font-weight:800}.eyebrow,em{color:#66808e;font-size:11px;font-style:normal;font-weight:800;letter-spacing:.11em;text-transform:uppercase}h1{font-size:27px;letter-spacing:-.03em;margin:0 0 4px}h2{font-size:17px;margin:4px 0}header p,section p{color:#6b7c87;margin:0}header small{margin-left:auto;color:#66808e}.steps{display:flex;align-items:center;color:#123b53;font-size:12px}.steps b{display:flex;gap:7px;align-items:center}.steps i{height:1px;background:#d6dfe3;flex:1;margin:0 12px}.track{background:#dfe6e9;border-radius:99px;height:4px;margin:8px 0 24px;overflow:hidden}.track span{display:block;height:100%;background:#b4cf31;transition:width .2s}.folder,section{background:#fff;border:1px solid #dce4e8;border-radius:12px;padding:20px;margin-bottom:16px;box-shadow:0 4px 16px #18384b0b}.folder{display:grid;grid-template-columns:1fr auto;gap:6px 18px;align-items:center}.folder code,.folder .muted{grid-column:1/-1;background:#f1f5f6;border-radius:6px;padding:10px 12px;overflow-wrap:anywhere;color:#355766}.field{margin-top:17px}.field label{display:block;font-weight:700;margin-bottom:6px}input,select,textarea{border:1px solid #c8d4da;border-radius:6px;width:100%;padding:10px 12px;font:inherit;color:inherit;background:#fff}input:focus,select:focus,textarea:focus,button:focus-visible{outline:3px solid #b4cf3155;outline-offset:2px;border-color:#779100}.bad input,.bad select,.bad textarea{border-color:#c64747}.field span,.error{display:block;color:#b23636;font-size:12px;margin-top:5px}button{border:0;border-radius:7px;cursor:pointer;font:inherit;font-weight:750;padding:10px 15px}.primary{background:#123b53;color:#fff;width:100%}.secondary{background:#edf3f4;color:#123b53}.success{background:#edf6d6;border:1px solid #d2e7a2;border-radius:12px;display:flex;gap:14px;padding:20px;color:#719100;font-weight:800}.success h2,.success p{margin:0;color:#16212b}.success p{font-weight:400;color:#4b6420}footer{text-align:center;color:#8a99a3;font-size:11px;padding-top:18px}footer strong{color:#5f7079}@media(max-width:520px){main{padding:25px 16px}.folder{grid-template-columns:1fr}.secondary{width:100%}}</style>
