<script>
  import { onMount } from 'svelte'
  import { invoke } from '@tauri-apps/api/core'
  import { open } from '@tauri-apps/plugin-dialog'
  let forms = {}, values = {}, installDir = '', error = '', done = false, busy = false
  onMount(async () => { try { forms = await invoke('get_forms_json') } catch { forms = {} }; for (const [name, form] of Object.entries(forms)) { values[name] = {}; for (const field of form.fields || []) values[name][field.name] = '' } })
  const visible = (name, field) => !field.when || values[name]?.[field.when.field] === field.when.value
  function payload() { const out = {}; for (const [name, form] of Object.entries(forms)) { out[name] = {}; for (const field of form.fields || []) if (visible(name, field)) out[name][field.name] = values[name][field.name] || '' }; return out }
  function valid(field, value, name) { if (field.required && !value.trim()) return `${field.name} is required`; if (field.type === 'email' && value && !/^\S+@\S+\.\S+$/.test(value)) return `${field.name} must be a valid email`; if (field.confirmation && value !== values[name]?.[field.confirmation]) return `${field.name} does not match ${field.confirmation}`; return '' }
  async function install() { error = ''; if (!installDir) { error = 'Choose an install folder'; return }; for (const [name, form] of Object.entries(forms)) for (const field of form.fields || []) if (visible(name, field) && (error = valid(field, values[name][field.name] || '', name))) return; busy = true; try { await invoke('collect_forms', { forms: payload() }); await invoke('verify_before_extract'); await invoke('extract_payload', { destDir: installDir }); done = true } catch (e) { error = String(e) } finally { busy = false } }
  async function choose() { const selected = await open({ directory: true, multiple: false }); if (typeof selected === 'string') installDir = selected }
</script>
<main><h1>Anvil Installer</h1>{#if !done}<button on:click={choose}>Choose install folder</button>{#if installDir}<code>{installDir}</code>{/if}{#each Object.entries(forms) as [name, form]}<section><h2>{form.title || name}</h2>{#each form.fields || [] as field}{#if visible(name, field)}<label>{field.label || field.name}{field.required ? ' *' : ''}{#if field.type === 'select'}<select value={values[name][field.name]} on:change={(e)=>values[name][field.name]=e.target.value}>{#each field.options || [] as option}<option value={option}>{option}</option>{/each}</select>{:else if field.type === 'textarea'}<textarea value={values[name][field.name]} on:input={(e)=>values[name][field.name]=e.target.value}></textarea>{:else}<input type={field.type === 'number' ? 'number' : field.type === 'password' ? 'password' : field.type === 'email' ? 'email' : 'text'} value={values[name][field.name]} on:input={(e)=>values[name][field.name]=e.target.value}>{/if}</label>{/if}{/each}</section>{/each}<button disabled={busy} on:click={install}>{busy ? 'Installing…' : 'Install'}</button>{:else}<p>Installation complete.</p>{/if}{#if error}<p class="error">{error}</p>{/if}</main>
<style>main{font-family:system-ui;padding:2rem;max-width:42rem;margin:auto}section{margin:1.5rem 0}label{display:flex;flex-direction:column;gap:.25rem;margin:.75rem 0}input,select,textarea{padding:.5rem;font:inherit}button{padding:.6rem 1rem;margin:.5rem .5rem .5rem 0}.error{color:#b00020}code{display:block;margin:.75rem 0;overflow-wrap:anywhere}</style>
