package execution

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"sync"
)

// ExecutionID uniquely identifies a single execution within the system.
//
// IDs are generated by MutableObserver when an execution is started and
// are used to query the status and result of that execution.
//
// Reference: TS-P6-06
type ExecutionID string

// String returns the string representation of the execution ID.
func (id ExecutionID) String() string {
	return string(id)
}

// Observer provides read-only access to the status and result of process
// executions. It is the interface for programmatic consumers that need
// to observe execution progress without managing execution directly.
//
// Implementations must be safe for concurrent access.
//
// Reference: TS-P6-06, EPIC-006
type Observer interface {
	// GetStatus returns the current lifecycle stage of the identified
	// execution. Returns an error if the execution ID is unknown.
	GetStatus(id ExecutionID) (Stage, error)

	// GetResult returns the execution result, blocking until it is
	// available. Returns an error if the execution ID is unknown.
	GetResult(id ExecutionID) (Result, error)

	// IsRunning returns true if the identified execution is currently
	// in the running stage. Returns false if the ID is unknown.
	IsRunning(id ExecutionID) bool

	// IsComplete returns true if the identified execution has reached
	// a terminal stage (completed, result available, or failed).
	// Returns false if the ID is unknown.
	IsComplete(id ExecutionID) bool
}

// MutableObserver implements the Observer interface and manages multiple
// process executions concurrently. Each execution is assigned a unique ID
// and tracked via a Lifecycle instance.
//
// Usage pattern:
//
//	observer := execution.NewMutableObserver(execution.NewRunner())
//	id, _ := observer.Start(ctx, req)
//	stage, _ := observer.GetStatus(id)
//	result, _ := observer.GetResult(id)
//
// Reference: TS-P6-06
type MutableObserver struct {
	mu         sync.Mutex
	runner     Runner
	lifecycles map[ExecutionID]*Lifecycle
}

// NewMutableObserver creates a MutableObserver that wraps the given Runner.
//
// The observer manages its own lifecycle tracking for each execution
// started via Start.
func NewMutableObserver(runner Runner) *MutableObserver {
	return &MutableObserver{
		runner:     runner,
		lifecycles: make(map[ExecutionID]*Lifecycle),
	}
}

// Start launches an execution and returns a unique ExecutionID that can
// be used to query the status and result via the Observer interface.
//
// The execution runs in a background goroutine. The caller may use
// GetStatus and GetResult to track progress.
//
// Returns an error if the execution request is invalid.
//
// Reference: TS-P6-06 AC1, AC2
func (m *MutableObserver) Start(ctx context.Context, req ExecutionRequest) (ExecutionID, error) {
	// Validate the request before proceeding.
	if err := req.Validate(); err != nil {
		return "", fmt.Errorf("invalid execution request: %w", err)
	}

	id := newExecutionID()

	lc := NewLifecycleRunner(m.runner)
	lc.setExecutionID(id)

	m.mu.Lock()
	m.lifecycles[id] = lc
	m.mu.Unlock()

	// Execute in background goroutine.
	go lc.Execute(ctx, req)

	return id, nil
}

// GetStatus returns the current lifecycle stage of the identified execution.
//
// Returns ErrExecutionNotFound if the execution ID is unknown.
//
// Reference: TS-P6-06 AC1, AC3
func (m *MutableObserver) GetStatus(id ExecutionID) (Stage, error) {
	m.mu.Lock()
	lc, ok := m.lifecycles[id]
	m.mu.Unlock()

	if !ok {
		return 0, fmt.Errorf("execution %s: %w", id, ErrExecutionNotFound)
	}

	return lc.Stage(), nil
}

// GetResult returns the execution result, blocking until it is available.
//
// Returns ErrExecutionNotFound if the execution ID is unknown.
//
// Reference: TS-P6-06 AC2, AC4
func (m *MutableObserver) GetResult(id ExecutionID) (Result, error) {
	m.mu.Lock()
	lc, ok := m.lifecycles[id]
	m.mu.Unlock()

	if !ok {
		return Result{}, fmt.Errorf("execution %s: %w", id, ErrExecutionNotFound)
	}

	return lc.Result(), nil
}

// IsRunning returns true if the identified execution is currently in the
// running stage.
//
// Returns false if the execution ID is unknown.
//
// Reference: TS-P6-06 AC1
func (m *MutableObserver) IsRunning(id ExecutionID) bool {
	m.mu.Lock()
	lc, ok := m.lifecycles[id]
	m.mu.Unlock()

	if !ok {
		return false
	}

	return lc.Stage() == StageRunning
}

// IsComplete returns true if the identified execution has reached a
// terminal stage (completed or result available).
//
// Returns false if the execution ID is unknown.
//
// Reference: TS-P6-06 AC1
func (m *MutableObserver) IsComplete(id ExecutionID) bool {
	m.mu.Lock()
	lc, ok := m.lifecycles[id]
	m.mu.Unlock()

	if !ok {
		return false
	}

	stage := lc.Stage()
	return stage == StageCompleted || stage == StageResultAvailable
}

// newExecutionID generates a cryptographically random hex string suitable
// for use as an execution identifier.
func newExecutionID() ExecutionID {
	b := make([]byte, 16)
	_, _ = rand.Read(b) // crypto/rand.Read never returns an error on modern systems
	return ExecutionID(hex.EncodeToString(b))
}

// ErrExecutionNotFound is returned when an execution ID does not match
// any known execution.
var ErrExecutionNotFound = fmt.Errorf("execution not found")
