#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]
use flate2::read::GzDecoder;
use serde_json::Value;
use sha2::{Digest, Sha256};
use std::{env,fs,path::{Component,Path,PathBuf}};
use tar::Archive;
use tauri::Manager;
const A:&str="resources/installer-artifact.tar.gz"; const H:&str="resources/installer-artifact.sha256"; const F:&str="resources/forms.json";
fn res(app:&tauri::AppHandle,n:&str)->Result<PathBuf,String>{app.path().resolve(n,tauri::path::BaseDirectory::Resource).map_err(|e|e.to_string())}
fn safe(root:&Path,p:&Path)->Result<PathBuf,String>{if p.is_absolute(){return Err("absolute archive path rejected".into())} let mut q=PathBuf::new(); for c in p.components(){match c{Component::Normal(x)=>q.push(x),Component::CurDir=>{},_=>return Err("path traversal rejected".into())}};if q.as_os_str().is_empty(){return Err("empty archive path rejected".into())} Ok(root.join(q))}
#[tauri::command] fn get_forms_json(app:tauri::AppHandle)->Result<Value,String>{let p=res(&app,F)?;if !p.exists(){return Ok(Value::Object(Default::default()))} serde_json::from_slice(&fs::read(p).map_err(|e|e.to_string())?).map_err(|e|e.to_string())}
#[tauri::command] fn apply_setup(app:tauri::AppHandle,forms:Value,dest_dir:String)->Result<String,String>{let setup:Value=serde_json::from_slice(&fs::read(res(&app,"resources/setup.json")?).map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;let root=PathBuf::from(&dest_dir);if !root.is_absolute(){return Err("install path must be absolute".into())}let env_path=root.join(setup.get("env_file").and_then(Value::as_str).unwrap_or(".env"));let mut out=if env_path.exists(){fs::read_to_string(&env_path).map_err(|e|e.to_string())?}else{String::new()};for(k,t)in setup.get("env_map").and_then(Value::as_object).cloned().unwrap_or_default(){let mut v=t.as_str().unwrap_or_default().to_string();if let Some(i)=v.strip_prefix("{{forms.").and_then(|x|x.strip_suffix("}}")){let mut p=i.splitn(2,'.');v=forms.get(p.next().unwrap_or_default()).and_then(|x|x.get(p.next().unwrap_or_default())).and_then(Value::as_str).unwrap_or_default().to_string()}let prefix=format!("{k}=");let line=format!("{k}={v}");let mut lines:Vec<String>=out.lines().map(str::to_owned).collect();if let Some(pos)=lines.iter().position(|x|x.starts_with(&prefix)){lines[pos]=line}else{lines.push(line)}out=lines.join("\n")+"\n"}if let Some(p)=env_path.parent(){fs::create_dir_all(p).map_err(|e|e.to_string())?}fs::write(&env_path,out).map_err(|e|e.to_string())?;eprintln!("[installer-gui] setup applied (redacted) env_keys_only");Ok(env_path.to_string_lossy().into())}
#[tauri::command] fn choose_install_dir(path:String)->Result<String,String>{let p=PathBuf::from(path);if !p.is_absolute(){return Err("install path must be absolute".into())}fs::create_dir_all(&p).map_err(|e|e.to_string())?;Ok(p.to_string_lossy().into())}
#[tauri::command] fn collect_forms(forms:Value)->Result<String,String>{let p=env::var("INSTALLER_FORMS_JSON").unwrap_or("/tmp/installer-forms.json".into());fs::write(&p,serde_json::to_vec_pretty(&forms).map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;#[cfg(unix)]{use std::os::unix::fs::PermissionsExt;fs::set_permissions(&p,fs::Permissions::from_mode(0o600)).map_err(|e|e.to_string())?;}eprintln!("[installer-gui] forms collected (redacted)");Ok(p)}
#[tauri::command] fn verify_before_extract(app:tauri::AppHandle)->Result<bool,String>{let p=res(&app,A)?;let expected=fs::read_to_string(res(&app,H)?).map_err(|e|e.to_string())?;let mut h=Sha256::new();h.update(fs::read(&p).map_err(|e|e.to_string())?);if format!("{:x}",h.finalize())!=expected.trim(){return Err("artifact checksum mismatch — verification failed closed".into())}Ok(true)}
#[tauri::command] fn extract_payload(app:tauri::AppHandle,dest_dir:String)->Result<String,String>{verify_before_extract(app.clone())?;let root=PathBuf::from(&dest_dir);if !root.is_absolute(){return Err("install path must be absolute".into())}fs::create_dir_all(&root).map_err(|e|e.to_string())?;let mut ar=Archive::new(GzDecoder::new(fs::File::open(res(&app,A)?).map_err(|e|e.to_string())?));for x in ar.entries().map_err(|e|e.to_string())?{let mut e=x.map_err(|e|e.to_string())?;let p=safe(&root,&e.path().map_err(|e|e.to_string())?)?;if let Some(parent)=p.parent(){fs::create_dir_all(parent).map_err(|e|e.to_string())?}e.unpack(&p).map_err(|e|e.to_string())?;}Ok(dest_dir)}
fn main(){if !cfg!(target_os="windows")&&!env::var("DISPLAY").is_ok()&&!env::var("WAYLAND_DISPLAY").is_ok(){eprintln!("GUI unavailable; use legacy TUI");std::process::exit(2)}tauri::Builder::default().plugin(tauri_plugin_dialog::init()).invoke_handler(tauri::generate_handler![get_forms_json,choose_install_dir,collect_forms,verify_before_extract,extract_payload,apply_setup]).run(tauri::generate_context!()).expect("native installer GUI")}
